colorMode()
colorMode(RGB)
colorMode(HSB)
colorMode(RGB, 1)
colorMode(RGB, 1, 2)
colorMode(RGB, 1, 2, 3)
colorMode(RGB, 1, 2, 3, 4)
colorMode(RGB, 1)
colorMode(RGB, 1, 1)
colorMode(RGB, 1, 1, 1)
colorMode(RGB, 1, 1, 1, 1)
